// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsqpvdrnzuqwbeptuzar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzcXB2ZHJuenVxd2JlcHR1emFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzA5ODQsImV4cCI6MjA3MDMwNjk4NH0.vJ8fw1NfaxdSzcDQFOUiDZWxNr12jNyJS7UO7FQYWb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});